<?php

/**
 * @file
 * Contains block_system.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Component\Serialization\Json;

/**
 * Implements hook_help().
 */

function block_system_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the block_system module.
    case 'help.page.block_system':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('My Awesome Module') . '</p>';
      return $output;

    default:
  }
}

function block_system_element_info_alter(array &$types) {
  if (isset($types['table'])) {
    $types['table']['#attached']['library'][] = 'block_system/table_library';
  }
}

function build () {
	$build['#attached']['library'][] = 'block_system/block_library';
}

function block_system_cron () {
	//Loading Block of type stock_exchange_rate_card
	$blocks = \Drupal::entityTypeManager()
		->getStorage('block_content')
		->loadByProperties(array('type' => 'stock_exchange_rate_card'));

	foreach ($blocks as $block) {
		//Inserting Symbol value into URL
		$value = $block->field_symbol->value;	
		$url = 'http://dev.markitondemand.com/MODApis/Api/v2/Quote/jsonp?symbol='.$value.'&callback=myFunction';

		//Using HTTP Client
		$client = \Drupal::httpClient();
		$request = $client->get('http://dev.markitondemand.com/MODApis/Api/v2/Quote/jsonp?symbol='.$value.'&callback=myFunction');
		$response = (string)$request->getBody();

		//Removing redundant data		
		$data = substr($response,11,strpos($response,")")-11);
		$decoded_data = Json::decode($data);

		$last_price = $decoded_data['LastPrice'];
		$change = $decoded_data['Change'];

		//Putting the values in Block Fields
		$block->set('field_change',$change);
		$block->set('field_last_price',$last_price);
		$block->save();

	}
}
